/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Player } from "./Player";
export type { PlayerStats } from "./PlayerStats";
export type { Treasury } from "./Treasury";
