/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as scroungeForSatoshisSol from "./ScroungeForSatoshis.sol";
export type { scroungeForSatoshisSol };
export type { BaseScheme } from "./BaseScheme";
export type { SchemeManager } from "./SchemeManager";
export type { YieldFarm } from "./YieldFarm";
